site_name: Marvin
site_description: 'The AI Engineering Framework'
site_copy: Marvin is a lightweight AI engineering framework for building natural language interfaces that are reliable, scalable, and easy to trust.
site_url: https://askmarvin.ai
docs_dir: docs
repo_url: https://github.com/prefecthq/marvin

nav:
  - Welcome:
    - welcome.md
  - Docs:
    - Configuration: 
      - Settings: configuration/settings.md
      - Providers: configuration/providers.md
    - Utilities: 
      - ChatCompletion: utilities/chat_completion.md
      - Prompt: utilities/prompt.md
    - Components: 
      - AI Function: components/ai_function.md
      - AI Model: components/ai_model.md
      - AI Classifier: components/ai_classifier.md
      - AI Application: components/ai_application.md


theme:
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    primary: custom
  name: material
  custom_dir: docs/overrides
  logo: img/logos/askmarvin_mascot.jpeg
  favicon: img/logos/askmarvin_mascot.jpeg

plugins:
  - search
  - markdownextradata

hooks:
  - docs/hooks.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
      title: On this page

extra:
  get_started: src/getting_started/what_is_marvin/
  hero:
    title: 'The AI Engineering Framework'
    description: 'Marvin is a lightweight AI engineering framework for building natural language interfaces that are reliable, scalable, and easy to trust.'
  announcement:
    title: 'Marvin 1.1: Anthropic, Azure, mapping, and instructions!'
    url: https://www.factsmachine.ai/p/marvin-11-more-ways-to-play
  analytics:
    provider: google
    property: G-2MWKMDJ9CM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prefecthq/marvin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Kgw4HpcuYG
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/askmarvinai


extra_css:
  - /static/css/global.css