site_name: Marvin
site_description: 'The AI Engineering Framework'
site_copy: Marvin is a lightweight AI engineering framework for building natural language interfaces that are reliable, scalable, and easy to trust.
site_url: https://askmarvin.ai
docs_dir: docs
repo_url: https://github.com/prefecthq/marvin

nav:
  - Getting Started:
    - welcome/what_is_marvin.md
    - welcome/quickstart.md
  - Use Cases:
    - Entity Deduplication: 
      - Location: examples/deduplication.md
    - Extraction:
      - Financial Figures: examples/financial_extraction.md
      - Meeting Notes and Action Items: examples/meeting_notes.md


theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    primary: custom
  name: material
  custom_dir: docs/overrides
  logo: img/logos/askmarvin_mascot.jpeg
  favicon: img/logos/askmarvin_mascot.jpeg

plugins:
  - search
  - markdownextradata
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS, false]
      cards_layout_options:
        font_family: Inter
        background_color: "#2d6df6"
  - awesome-pages
  - autolinks 
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: False
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            show_submodules: False
            show_if_no_docstring: False
            show_signature: False
            heading_level: 2
            filters: ["!^_"]

hooks:
  - docs/hooks.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - toc:
      permalink: true
      title: On this page

extra:
  get_started: welcome/what_is_marvin
  hero:
    title: 'The AI Engineering Framework'
    description: 'Marvin is a lightweight AI engineering framework for building natural language interfaces that are reliable, scalable, and easy to trust.'
  announcement:
    title: "Marvin 1.3 makes agents easy to debug"
    url: https://github.com/PrefectHQ/marvin/releases/tag/v1.3.0
  analytics:
    provider: google
    property: G-2MWKMDJ9CM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prefecthq/marvin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Kgw4HpcuYG
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/askmarvinai


extra_css:
  - /static/css/global.css
  - /static/css/badges.css
  - /static/css/custom.css