site_name: Marvin
site_url: https://askmarvin.ai
site_description: A batteries-included library for building AI-powered software.
nav:
  - Welcome: 
    - index.md
  - The Guide:
    - Components:
      - AI Models: guide/ai_components/ai_models.md
      - AI Functions: guide/ai_components/ai_functions.md
  - Examples: 
    - AI Models: examples/ai_models.md
  
theme:
  name: material
  font: 
    text: Inter
    code: JetBrains Mono
  logo: img/logos/askmarvin_mascot.jpeg
  favicon: img/logos/askmarvin_mascot.jpeg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - toc.follow
    - toc.integrate 
    - content.action.edit
    - content.code.copy
    - content.code.annotate 
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      # primary: green
      # accent: light blue
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      # primary: blue
      # accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS, false]
      cards_font: Inter
      cards_color:
        fill: "#2d6df6"
  - awesome-pages
  - autolinks 
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
              show_source: False
              show_root_heading: True
              show_object_full_path: False
              show_category_heading: False
              show_bases: False
              show_submodules: False
              show_if_no_docstring: False
              show_signature: False
              heading_level: 2
              filters: ["!^_"]
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
repo_url: https://github.com/prefecthq/marvin
edit_uri: edit/main/docs/
extra:
  analytics:
    provider: google
    property: G-2MWKMDJ9CM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prefecthq/marvin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Kgw4HpcuYG
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/askmarvinai
extra_css:
  - stylesheets/extra.css