site_name: Marvin
site_description: 'Marvin: The AI Engineering Framework'
site_copy: Marvin makes it easier to build AI-powered applications in a scalable, reliable, and secure way.
site_url: https://askmarvin.ai
docs_dir: docs
nav:
  - Motivation:
    - src/motivation.md
  - Tutorials:
    - src/tutorials.md
    - Natural Language Processing:
      - Extracting Structured Data:
        - src/notebooks/scraping.ipynb
      - src/tutorials/tutor.md
      - src/tutorials/assistant.md
    - Conversational Applications:
      - src/tutorials/chatbot.md
      - src/tutorials/assistant.md
      - src/tutorials/data.md
    - Autonomous Applications:
      - src/tutorials/smol.md
      - src/tutorials/autogpt.md
      - src/tutorials/workgpt.md
    - Games:
      - src/tutorials/startwars.md
      - src/tutorials/twentyquestions.md
      - src/tutorials/educational.md
  - How-Tos:
    - src/guides.md
    - Writing Prompts:
      - src/guides.md
    - Using Tools:
      - src/guides.md
    - Using Data:
      - src/guides.md
    - Deploying your Application:
      - src/guides.md
    - Orchestration:
      - src/guides.md
    - Observability:
      - src/guides.md
  - Reference:
    - src/reference/index.md
    - Prompts: 
      - src/reference/prompts.md
      - src/reference/prompts_execute.md
    - Components:
      - src/reference/ai_function.md
      - src/reference/ai_model.md
      - src/reference/ai_classifier.md
      - src/reference/ai_application.md
    - Applications:
      - src/reference/applications.md
    - Engines: 
      - src/reference/models.md
      - src/reference/executors.md
    - Configuration:
      - src/reference/configuration.md
    - Deployment:
      - src/reference/deployment.md
  - Community:
    - src/community.md
    - src/community_commit.md
  
theme:
  name: material
  custom_dir: docs/overrides
  font: 
    text: Inter
    code: JetBrains Mono
  logo: img/logos/askmarvin_mascot.jpeg
  favicon: img/logos/askmarvin_mascot.jpeg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.annotate 
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  palette:
    # Palette toggle for light mode
    - scheme: default
      # primary: green
      # accent: light blue
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      # primary: blue
      # accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
plugins:
  - search
  - mkdocs-jupyter
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS, false]
      cards_font: Inter
      cards_color:
        fill: "#2d6df6"
  - awesome-pages
  - autolinks 
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
              show_source: False
              show_root_heading: True
              show_object_full_path: False
              show_category_heading: False
              show_bases: False
              show_submodules: False
              show_if_no_docstring: False
              show_signature: False
              heading_level: 2
              filters: ["!^_"]
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
      title: On this page
      
repo_url: https://github.com/prefecthq/marvin
edit_uri: edit/main/docs/
extra:
  analytics:
    provider: google
    property: G-2MWKMDJ9CM
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/prefecthq/marvin
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Kgw4HpcuYG
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/askmarvinai
extra_css:
- static/css/termynal.css
- static/css/custom.css
extra_javascript:
- static/js/termynal.js
- static/js/custom.js