[tool.poetry]
name = "marvin"
version = "0.11.0"
description = ""
authors = []
readme = "README.md"
repository = "https://github.com/prefecthq/marvin"
homepage = "https://www.askmarvin.ai"
documentation = "https://www.askmarvin.ai"

[tool.poetry.dependencies]
datamodel-code-generator = { version = "^0.20.0", optional = true }
fastapi = "^0.98.0"
jinja2 = "^3.1.2"
openai = "^0.27.8"
pydantic = { extras = ["dotenv"], version = "^1.10.9" }
python = "^3.8"
rich = "^12"
tiktoken = "^0.4.0"
typer = "^0.9.0"
uvicorn = "^0.22.0"

[tool.poetry.extras]
generator = ["datamodel-code-generator"]

[tool.poetry.scripts]
marvin = "marvin.cli:app"

[tool.poetry.dev-dependencies]
pytest = "^7.2.2"
ruff = "^0.0.274"
jupyter = "^1.0.0"
notebook = "^6.5.4"

[tool.poetry.group.framework.dependencies]
aiosqlite = "^0.19.0"
alembic = "^1.11.1"
bcrypt = "^4.0.1"
gunicorn = "^20.1.0"
prefect = "^2.10.17"
sqlalchemy = "^2.0.17"

[tool.poetry.group.openai.dependencies]
openai = "^0.27.8"
tiktoken = "^0.4.0"

[tool.poetry.group.lancedb.dependencies]
lancedb = "^0.1.8"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


# black configuration
[tool.black]
preview = true


# ruff configuration
[tool.ruff]
extend-select = ["I"]


[tool.ruff.per-file-ignores]
"__init__.py" = ['I', 'F401', 'E402']
"conftest.py" = ["F401", "F403"]
'tests/fixtures/*.py' = ['F403']


[tool.pytest.ini_options]
markers = ["llm: indicates that a test calls an LLM (may be slow)."]

testpaths = ["tests"]

norecursedirs = [
    "*.egg-info",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".vscode",
    "node_modules",
]

asyncio_mode = 'auto'

filterwarnings = [
    "ignore:'crypt' is deprecated and slated for removal in Python 3.13:DeprecationWarning",
]
env = [
    "MARVIN_TEST_MODE=1",
    "MARVIN_LOG_LEVEL=DEBUG",
    "MARVIN_LOG_CONSOLE_WIDTH=120",
    # use 3.5 for tests by default
    "MARVIN_LLM_MODEL=gpt-3.5-turbo-0613",    
    "MARVIN_LLM_MODEL_TEMPERATURE=0"

]