[tool.poetry]
name = "marvin"
version = "0.11.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.98.0"
typer = "^0.9.0"
jinja2 = "^3.1.2"
uvicorn = "^0.22.0"
datamodel-code-generator = {version = "^0.20.0", optional = true}
rich = "^12"
pydantic = {extras = ["dotenv"], version = "^1.10.9"}
openai = "^0.27.8"

[tool.poetry.extras]
generator = ["datamodel-code-generator"]

[tool.poetry.scripts]
marvin = "marvin.cli:app"

[tool.poetry.dev-dependencies]
ruff = "^0.0.274"
jupyter = "^1.0.0"
notebook = "^6.5.4"

[tool.poetry.group.framework.dependencies]
prefect = "^2.10.17"
sqlalchemy = "^2.0.17"
bcrypt = "^4.0.1"
alembic = "^1.11.1"
aiosqlite = "^0.19.0"
gunicorn = "^20.1.0"

[tool.poetry.group.openai.dependencies]
openai = "^0.27.8"
tiktoken = "^0.4.0"

[tool.poetry.group.lancedb.dependencies]
lancedb = "^0.1.8"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# black configuration
[tool.black]
preview = true

# ruff configuration
[tool.ruff]
extend-select = ["I"]

[tool.ruff.per-file-ignores]
"__init__.py" = ['I', 'F401', 'E402']
"conftest.py" = ["F401", "F403"]
'tests/fixtures/*.py' = ['F403']
