name: Publish Docs

on:
  push:
    branches: ["main"]
    tags: 
      - 'v*'
  workflow_dispatch:

env:
  MKDOCS_SOCIAL_CARDS: ${{ vars.MKDOCS_SOCIAL_CARDS }}
  MKDOCS_MATERIAL_INSIDERS_REPO_RO: ${{ secrets.MKDOCS_MATERIAL_INSIDERS_REPO_RO }}

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install dependencies for MKDocs Material
        run: pip install \
          mkdocs-material \
          mkdocs-autolinks-plugin \
          mkdocs-awesome-pages-plugin \
          mkdocstrings[python] \
          mkdocs-markdownextradata-plugin \
          mkdocs-jupyter \
          pillow \
          cairosvg \
          mike
      - name: Publish docs from `main` to dev
        if: github.ref == 'refs/heads/main'
        run: mike deploy dev --push --update-aliases

      - name: Publish versioned docs
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')
          mike deploy $VERSION latest --push --update-aliases
