name: Publish Marvin to PyPI

on:
  push:
    branches: 
      - main
      - marvin-old

jobs:
  publish-pypi-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build

      - name: Publish package
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/marvin-old'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
